# Generated by Django 4.1 on 2022-09-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_multipleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.FileField(upload_to='folder'),
        ),
        migrations.AlterField(
            model_name='webimage',
            name='image',
            field=models.ImageField(upload_to='webPics'),
        ),
    ]
