# Generated by Django 4.1 on 2022-09-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_remove_webimage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
        migrations.AddField(
            model_name='person',
            name='Address',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='Contact',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='Department',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='Name',
            field=models.CharField(default='Some String', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='Photo',
            field=models.ImageField(default='Personal_tof', upload_to='Personal_tof'),
        ),
        migrations.AddField(
            model_name='person',
            name='School',
            field=models.CharField(default='Some String', max_length=200),
        ),
    ]
